# 1.4.9 Contours in OpenCV

<h3>
    <ul>
        <li>Understand what contours are</li>
        <li>Learn to fend contours, draw contours etc</li>
        <li>You will see these functions : cv2.findContours(), cv2.drawContours()</li>
    </ul>
</h3>

In [7]:
import numpy as np
import cv2

im = cv2.imread('Ras.png')
imgray = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
imgray = 255 - imgray

ret, thresh = cv2.threshold(imgray, 127, 255, 0)

kernel = np.ones((5, 5), np.uint8)
clossing = cv2.morphologyEx(im, cv2.MORPH_CLOSE, kernel)

contours, hierychal = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
im = cv2.drawContours(im, contours, -1, (0, 100, 0), 3)
im = cv2.drawContours(im, contours, 0, (0, 200, 0), 3)
im = cv2.drawContours(im, contours, 1, (200, 0, 0), 3)
im = cv2.drawContours(im, contours, 2, (0, 0, 255), 3)

controus, hierarchy = cv2.findContours(thresh, 1, 2)

cnt = contours[0]
M = cv2.moments(cnt)

cx = int(M['m10']/M['m00'])
cy = int(M['m01']/M['m00'])

area = cv2.contourArea(cnt)

perimeter = cv2.arcLength(cnt, True)

epsilon = 0.1 * cv2.arcLength(cnt, True)
approx = cv2.approxPolyDP(cnt, epsilon, True)

im = cv2.circle(im, (cx, cy), 4, (255, 0, 0), -1)

font = cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(im, 'A'+str(area)+", L"+str(perimeter), (cx, cy), font, 1, (0, 0, 0), 2, cv2.LINE_AA)

cv2.imshow('contours', im)
cv2.waitKey(0)
cv2.destroyAllWindows()



In [3]:
import numpy as np
import cv2

im = cv2.imread('Ras.png')
imgray = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold (imgray, 127, 255, 0)
contours, hierarchy = cv2.findContours (thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)



<h3>
    <ul>
        <li>To find the different features of contours, like area, perimeter, centroid, bounding box etc</li>
        <li>You will see plenty of functions related to contours</li>
    </ul>
</h3>

#### 1.Moments

In [71]:
import cv2
import numpy as np

img = cv2.imread ('hand.jpg')
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
imgray = 255 - imgray
blur = cv2.blur (imgray, (5, 5))

ret, thresh = cv2.threshold (blur, 20, 255, cv2.THRESH_BINARY)
'''
cv2.imshow('th', thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()
'''

contours, hierarchy = cv2.findContours (thresh, 1, 2)

im = cv2.drawContours(img, contours, -1, (0, 100, 0), 3)

cv2.imshow('contours', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

cnt = contours [0]
M = cv2.moments (cnt)
print (M)

cx = int (M['m10']//M['m00'])
cy = int (M['m01']//M['m00'])

area = cv2.contourArea (cnt)

perimeter = cv2.arcLength (cnt, True)

epsilon = 0.1 * cv2.arcLength (cnt, True)
approx = cv2.approxPolyDP (cnt, epsilon, True)

hull = cv2.convexHull (cnt)
print (hull)
print (cnt[0])

k = cv2.isContourConvex(cnt)
print (k)

x, y, w, h = cv2.boundingRect (cnt)
aspect_ratio = float (w) / h

img = cv2.rectangle (img, (x,y), (x+w, y+h), (0, 255, 0), 2)

cnt = contours [0]

rect = cv2.minAreaRect (cnt)
box = cv2.boxPoints (rect)
box = np.int0(box)
img = cv2.drawContours (img, [box], 0, (0, 0, 255), 2)

cnt = contours [0]

(x, y), radius = cv2.minEnclosingCircle(cnt)
center = (int (x), int (y))
radius = int (radius)
img = cv2.circle (img, center, radius, (0, 255, 0), 2)

cnt = contours [0]

ellipse = cv2.fitEllipse(cnt)
img = cv2.ellipse (img, ellipse, (0, 255, 0), 2)

cnt = contours [0]

rows, cols = img.shape[:2]
[vx, vy, x, y] = cv2.fitLine (cnt, cv2.DIST_L2, 0, 0.01, 0.01)
lefty = int ((-x*vy/vx) + y)
righty = int (((cols - x) * vy / vx) + y)
img = cv2.line (img, (cols-1, righty), (0, lefty), (0, 255, 0), 2)

cv2.imshow('contours', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

{'m00': 209049.5, 'm10': 120007113.16666666, 'm01': 61719484.5, 'm20': 81252657333.91666, 'm11': 31210173573.958332, 'm02': 21019085557.25, 'm30': 61310817530105.95, 'm21': 18804524173493.883, 'm12': 9668829525689.482, 'm03': 7871039780472.15, 'mu20': 12361283709.023315, 'mu11': -4220560108.637554, 'mu02': 2797110537.239235, 'mu30': 474600319962.9297, 'mu21': -338681888881.33984, 'mu12': 94742093210.56299, 'mu03': 13764034054.614258, 'nu20': 0.28285594294178557, 'nu11': -0.09657658034332788, 'nu02': 0.06400462582584965, 'nu30': 0.02375227395996374, 'nu21': -0.016949978058623985, 'nu12': 0.004741547906359363, 'nu03': 0.000688847212924349}
[[[1022    2]]

 [[1022  247]]

 [[ 512  511]]

 [[ 507  513]]

 [[ 500  515]]

 [[ 449  527]]

 [[ 440  529]]

 [[ 430  531]]

 [[ 412  533]]

 [[ 396  533]]

 [[ 362  532]]

 [[ 296  526]]

 [[ 292  525]]

 [[ 289  524]]

 [[ 112  460]]

 [[  98  453]]

 [[  92  447]]

 [[  92  444]]

 [[ 125  354]]

 [[ 157  287]]

 [[ 160  284]]

 [[ 162  283]]

 [